import json

def apply_refactor():
    with open("beijing_air_quality.ipynb", "r") as f:
        nb = json.load(f)

    # Add modeling and evaluation functions
    mod_markdown = {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Modeling & Evaluation Functions\n",
            "This section contains wrapper functions to streamline the training and evaluation of various models: Baselines, Trees, and Deep Learning."
        ]
    }

    mod_functions = {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "def evaluate_models(y_true, predictions_dict):\n",
            "    \"\"\"\n",
            "    Evaluates multiple models against the true values using standard regression metrics.\n",
            "    \n",
            "    Args:\n",
            "        y_true (np.array): Ground truth target values.\n",
            "        predictions_dict (dict): Dictionary mapping model names to their predictions.\n",
            "        \n",
            "    Returns:\n",
            "        pd.DataFrame: A dataframe containing evaluation metrics for each model.\n",
            "    \"\"\"\n",
            "    results = {}\n",
            "    for name, y_pred in predictions_dict.items():\n",
            "        # Align lengths if sequence generation chopped off the first n_steps\n",
            "        if len(y_pred) != len(y_true):\n",
            "            diff = len(y_true) - len(y_pred)\n",
            "            y_true_aligned = y_true[diff:]\n",
            "        else:\n",
            "            y_true_aligned = y_true\n",
            "            \n",
            "        results[name] = {\n",
            "            'MAE': mean_absolute_error(y_true_aligned, y_pred),\n",
            "            'MSE': mean_squared_error(y_true_aligned, y_pred),\n",
            "            'RMSE': root_mean_squared_error(y_true_aligned, y_pred)\n",
            "        }\n",
            "    \n",
            "    df_results = pd.DataFrame(results).T\n",
            "    return df_results\n",
            "\n",
            "def train_tree_models(X_train, y_train, X_test, y_test):\n",
            "    \"\"\"\n",
            "    Trains a set of tree-based models and returns their predictions.\n",
            "    \n",
            "    Args:\n",
            "        X_train, y_train, X_test, y_test: Training and testing data splits.\n",
            "        \n",
            "    Returns:\n",
            "        dict: Predictions from the models.\n",
            "    \"\"\"\n",
            "    predictions = {}\n",
            "    \n",
            "    # Random Forest\n",
            "    rf = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)\n",
            "    rf.fit(X_train, y_train)\n",
            "    predictions['RandomForest'] = rf.predict(X_test)\n",
            "    \n",
            "    # HistGradientBoosting (Fast for large datasets)\n",
            "    hgb = HistGradientBoostingRegressor(random_state=42)\n",
            "    hgb.fit(X_train, y_train)\n",
            "    predictions['HistGradientBoosting'] = hgb.predict(X_test)\n",
            "    \n",
            "    return predictions\n",
            "\n",
            "def train_deep_learning_models(X_train_seq, y_train_seq, X_val_seq, y_val_seq, X_test_seq, input_shape):\n",
            "    \"\"\"\n",
            "    Trains standard deep learning models (RNN, LSTM, CNN) for time series forecasting.\n",
            "    \n",
            "    Args:\n",
            "        X_train_seq... : Sequence arrays generated by create_sequences.\n",
            "        input_shape (tuple): Shape of the input sequences (sequence_length, n_features).\n",
            "        \n",
            "    Returns:\n",
            "        dict: Predictions from the models.\n",
            "    \"\"\"\n",
            "    predictions = {}\n",
            "    early_stop = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)\n",
            "    \n",
            "    # Simple RNN\n",
            "    rnn = Sequential([\n",
            "        Input(shape=input_shape),\n",
            "        SimpleRNN(64, return_sequences=False),\n",
            "        Dropout(0.2),\n",
            "        Dense(1)\n",
            "    ])\n",
            "    rnn.compile(optimizer='adam', loss='mse', metrics=['mae'])\n",
            "    rnn.fit(X_train_seq, y_train_seq, validation_data=(X_val_seq, y_val_seq), epochs=10, batch_size=256, callbacks=[early_stop], verbose=0)\n",
            "    predictions['RNN'] = rnn.predict(X_test_seq, verbose=0).flatten()\n",
            "    \n",
            "    # LSTM\n",
            "    lstm = Sequential([\n",
            "        Input(shape=input_shape),\n",
            "        LSTM(64, return_sequences=False),\n",
            "        Dropout(0.2),\n",
            "        Dense(1)\n",
            "    ])\n",
            "    lstm.compile(optimizer='adam', loss='mse', metrics=['mae'])\n",
            "    lstm.fit(X_train_seq, y_train_seq, validation_data=(X_val_seq, y_val_seq), epochs=10, batch_size=256, callbacks=[early_stop], verbose=0)\n",
            "    predictions['LSTM'] = lstm.predict(X_test_seq, verbose=0).flatten()\n",
            "    \n",
            "    return predictions\n"
        ]
    }

    # Insert before "# Baseline Models"
    insert_idx = -1
    for i, cell in enumerate(nb["cells"]):
        if cell["cell_type"] == "markdown" and "# Baseline Models" in "".join(cell.get("source", [])):
            insert_idx = i
            break

    if insert_idx != -1:
        nb["cells"].insert(insert_idx, mod_markdown)
        nb["cells"].insert(insert_idx + 1, mod_functions)

    with open("beijing_air_quality.ipynb", "w") as f:
        json.dump(nb, f, indent=2)

apply_refactor()
